node_js:
- "4"
- "5"
language: node_js
before_install: nvm ls-remote
install: npm install
before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: npm run travis